buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.27'
    }
}

apply plugin: 'net.minecraftforge.gradle'

minecraft {
    mappings channel: 'official', version: '1.21.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.mojanglevels', 'info'
            mods {
                afkmod {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.21.1-52.0.0'
}
